package-lock.json, package.json, src/utils/cn.ts
> - #4 
**tailwind 관련 라이브러리 설치**
- clsx 설치
- cva 설치
- twMerge 설치
**유틸 함수 정의**
- cn 함수 정의
cn 함수
- https://polyframe.tistory.com/142
=> chore: tailwind 관련 라이브러리 설치

app/page.tsx, package-lock.json, package.json, src/components/common/button.tsx
> - #7 
- 버튼 컴포넌트를 제작합니다.
- cva 라이브러리를 설치합니다.
=> feat: 버튼 컴포넌트 제작

src/components/common/chat-bubble.tsx
=> feat: 공통컴포넌트 말풍선 모양 변경

app/account/find-id/page.tsx, app/account/find-pw/page.tsx, app/account/login/page.tsx, app/account/register/page.tsx, package-lock.json, package.json, src/components/common/input.tsx, src/schema/user.ts
> - #3 
- react hook form을 기반으로 하는 input 공통 컴포넌트를 제작합니다.
- zod를 통해 유효성 검사 및 에러 메시지를 반환합니다.
- login 페이지를 구현하였고, 그와 연결된 페이지를 추가하였습니다.
https://github.com/user-attachments/assets/15848718-8396-463d-8148-13a4e076ed93
=> feat: Input 컴포넌트 제작

app/page.tsx, src/components/common/default-profile.tsx, src/components/common/profile.tsx
> 관련된 이슈를 태그해주세요 ex) #17 
- 기본 프로필을 제작합니다
- 매칭 리스트 프로필로 사용됩니다.
- 프로필 이미지 컴포넌트를 제작합니다.
=> feat: 공통 컴포넌트 프로필 제작

package-lock.json, package.json, src/components/common/modal-one-btn.tsx, src/components/common/modal-two-btn.tsx, tailwind.config.ts
=> chore: radix ui 설치

app/page.tsx, src/components/common/multiple-selection.tsx
> #26 
- multiple selection 제작
- use client 모드
=> feat: 공통 컴포넌트 multiple selection 제작

package-lock.json, package.json, patches/react-select+5.10.1.patch
- #39 
🔨 작업 내용
> **이슈: 'aria-activedescendant' 불일치 오류**
> - Server -> aria-activedescendant가 undefined
> - Client -> aria-activedescendant가 '' (빈 문자열)
react-select에서 발생하는 hydration 오류를 해결하였습니다.
- React Select 라이브러리의 자체적인 문제라서 node_modules를 직접 수정
patch package 라이브러리를 설치하였습니다.
- node_modules를 직접 수정할 경우, 수정한 내용이 사라질 수 있음
- 수정 내용을 저장하기 위해 해당 라이브러리 사용
=> fix: react select hydration 오류 픽스

app/(top-layout)/chat/page.tsx, src/components/chat/chat-window.tsx, src/components/common/profile.tsx
=> fix: build 오류 해결

app/(main-layout)/notifications/page.tsx, package-lock.json, src/components/common/connect-on-banner.tsx, src/components/common/radix-tabs.tsx
-  페이지 탭바 비율 조정
- 공통 컴포넌트 생성(알림배너)
=> Feat: 알림배너 공통 컴포넌트로 따로 분배, 페이지 너비 수정 

public/sw.js, src/components/chat/chat-window.tsx, src/components/notifications/notify-card.tsx
=> fix: 빌드 에러 수정

app/(plain)/qr-reader/page.tsx, app/test/page.tsx, src/stores/use-card-store.ts, src/types/form.ts, src/utils/use-form-submit.ts
> - #74 
- QR 코드 스캔 시 명함이 추가됩니다.
- mypage 작업이 덜 되어 일단 session storage에 추가되는 부분까지만 구현을 해두었습니다.
- 화질 문제인지... gpt가 생성한 QR은 잘 스캔되는데, 페이지에서 캡쳐한 QR은 스캔되지 않는 문제가 있습니다 😢
=> feat: 명함 교환 기능 구현

next.config.ts, package-lock.json, package.json
> - #96 
- proxy 설정
- axios 설치
=> feat: axios 추가 및 proxy 설정

app/api/send-push/route.ts, app/page.tsx, app/test/page.tsx, package-lock.json, package.json, public/firebase-messaging-sw.js, src/components/notification-button.tsx, src/stores/use-network-store.ts, src/utils/firebase/firebase.ts, src/utils/firebase/get-fcm-token.ts, src/utils/firebase/request-permission.ts
> - #104 
- 웹 푸시 알림 테스트 O
- 아이폰 푸시 알림 테스트 진행해야 함
- 안드로이드 푸시 알림 테스트 진행해야 함
=> feat: 푸시 알림 테스트

app/(plain)/qr-reader/page.tsx, app/test/page.tsx, src/stores/use-network-store.ts, src/utils/api/send-push.ts
=> fix: 빌드 오류 해결

.gitignore, middleware.ts, vercel.json
> - #108 
- proxy 미작동으로 인한 proxy 에러
=> fix: vercel proxy 에러

app/(main-layout)/home/page.tsx, app/(top-layout)/create-group/page.tsx, package-lock.json, package.json, src/components/card/match-card.tsx, src/components/card/match-group.tsx, src/components/card/match-one-to-one.tsx, src/components/common/default-profile.tsx, src/components/common/profile-important.tsx, src/components/match/career-slider.tsx, src/components/match/group.tsx, src/components/mypage/card-item.tsx, src/stores/use-group-match-store.ts, src/styles/globals.css, src/types/group.types.ts, src/types/user.types.ts, src/utils/get-top-nav-type.ts
=> fix: 빌드오류 수정

app/(main-layout)/home/page.tsx, app/(top-layout)/chat/page.tsx, src/components/chat/chat-bubble.tsx
하드 코딩되어있던 채팅 부분 실제 데이터로 대체
채팅 요청 -> 채팅 수락 시에 채팅 페이지 이동 -> 채팅
이 플로우까지 가능한 상태입니다.
=> feat: 채팅 기능 구현

app/(top-layout)/create-group/page.tsx, app/(top-layout)/ios-notification/page.tsx, app/test-api/page.tsx, package-lock.json, package.json, src/components/common/quick-network/icon-rolling.tsx, src/components/common/quick-network/text.rolling.tsx, src/components/match/group.tsx, src/components/mypage/detail-card.tsx, src/components/register/toggle-field.tsx, src/utils/api/user.ts
> #138 
- 관심인원 연결
- 색상 랜덤값 겹치지않게 변경
=> feat: quick-network 수정사항

app/(top-layout)/chat/page.tsx, src/components/register/toggle-field.tsx
=> feat: 채팅방 나가기 기능 추가

app/(top-layout)/networking-qr-reader/page.tsx, app/(top-layout)/qr-reader/page.tsx, src/components/common/qr-scanner.tsx, src/components/table/networking-button.tsx, src/utils/api/network.ts, src/utils/get-top-nav-type.ts
> - #156 
- 네트워킹 시작 버튼
- 버튼 누르면 테이블 스캐너로 이동 
- 스캔 시 네트워킹 시작 
handleNetworkingStart
- table -> 다이나믹 라우트가 필요한지, 없어도 되는지 잘 모르겠어서 이 부분은 추가 안 했습니다..
- 페이지 이동해야 되면 networkingStart(parsedData.tableNumber); 아래에 router 추가해주세요~!
=> feat: 네트워킹 시작 버튼

app/(main-layout)/home/page.tsx, app/(top-layout)/create-group/page.tsx, src/assets/svgs/qr-code-ver1.svg, src/components/common/top-nav.tsx, src/components/match/career-slider.tsx, src/components/match/group.tsx, src/components/register/toggle-field.tsx
> #159 
- 그룹 카드 ui
- 채팅 알림 ui
- qr-code svg 변경
- slider 기본값 설정
=> feat: 그룹 카드 ui 및 채팅알림 ui 구현

app/(main-layout)/home/page.tsx, app/(main-layout)/user-info/[userId]/page.tsx, app/(top-layout)/chat/page.tsx, src/components/match/modal-for-match.tsx, src/utils/websoket.ts
> - #162 
- protocol에 따라 ws or wss 설정되도록 로직 추가
- button variants 수정
=> feat: protocol에 따라 ws or wss 설정되도록 로직 추가

next.config.ts, vercel.json
> - #165 
- https/ http 환경에 맞게 요청
=> chore: config 수정

vercel.json
=> feat: https 루트 추가

next.config.ts, vercel.json
=> fix: config 변경

app/(main-layout)/layout.tsx, app/(top-layout)/layout.tsx, app/(top-layout)/networking-qr-reader/page.tsx, src/components/common/card-basic.tsx
=> fix: build error

app/(plain)/login/page.tsx, middleware.ts, next.config.ts
> - #184 
- 기본 페이지 /home으로 설정
- 루트 페이지 대신 login 페이지 추가
- middleware 추가 (로그인을 한 상태에서 /login으로 이동 불가, 로그인을 안 한 상태에서 /home으로 이동 불가 등)
=> feat: 미들웨어 설정 

app/(top-layout)/mypage/edit-profile/page.tsx, src/types/form.ts, src/utils/api/user.ts, src/utils/format-form-data.ts
> - #178
- 마이페이지에서 본인의 닉네임을 확인할 수 있습니다.
=> feat: 닉네임 확인 필드 추가

app/layout.tsx
=> chore: ios nav 컬러 변경

app/(main-layout)/home/page.tsx
> - #192 
- job Data 나오지 않는 오류 픽스
=> fix: job Data 나오지 않는 오류 픽스

src/components/match/group.tsx, src/stores/use-network-store.ts
- 그룹 채팅방 참여 시 참여 중으로 변경됨 
- useNetworkStore에 추가하여 전역 관리 
=> Feat: 그룹 채팅방 참여 시 참여 중으로 변경됨 

app/(top-layout)/create-group/page.tsx, src/components/match/group.tsx, src/types/group.types.ts
=> feat: 참여 상태 뱃지

app/(top-layout)/chat/page.tsx, src/components/chat/chat-window.tsx, src/components/chat/table-application-card.tsx
> 관련된 이슈를 태그해주세요 ex) #198 
- 1:1 채팅방에서 상대방 닉네임과 회사를 확인할 수 있습니다. 
- 테이블 카드 빈 공간을 없애고 화면 크기로 맞췄습니다. 
=> feat: 채팅방 상대방 유저 프로필 
